"""Pre-generated routine conversation prompts for each interest domain.

Each domain has ~30 prompts. Placeholders:
  {self}  — the speaking agent's first name
  {other} — the conversation partner's first name

These are selected deterministically at runtime (no LLM call).
"""

from __future__ import annotations

from typing import Dict, List

ROUTINE_PROMPTS: Dict[str, List[str]] = {
    # ------------------------------------------------------------------
    "family": [
        "You bump into {other} while picking up groceries. Catch up on how your families are doing.",
        "You and {other} are waiting for your kids at school pickup. Chat about parenting lately.",
        "You run into {other} at a neighbourhood barbecue. Talk about your siblings and what they've been up to.",
        "You're sitting with {other} at a cafe. Share how your parents are doing health-wise.",
        "You and {other} are at a community event. Discuss holiday plans with your families.",
        "You meet {other} at the park. Talk about a funny thing your kid or relative did recently.",
        "You and {other} are catching up after not seeing each other for a while. Share family news.",
        "You're on a walk with {other}. Bring up how your in-laws have been.",
        "You see {other} at the gym. Mention a family milestone — a birthday, graduation, or anniversary.",
        "You and {other} are grabbing lunch. Vent a little about a family disagreement.",
        "You meet {other} at a bookstore. Talk about a family tradition you've been keeping up.",
        "You and {other} are at a dinner party. Discuss how your extended family dynamics have shifted.",
        "You run into {other} on the bus. Share news about a relative who just moved to a new city.",
        "You and {other} are at a playground. Compare notes on how your kids' school years are going.",
        "You see {other} at a farmers market. Talk about a recipe your grandmother used to make.",
        "You and {other} are waiting in line. Chat about planning a family reunion.",
        "You bump into {other} at the library. Mention a family photo album you found while cleaning.",
        "You and {other} are at a block party. Talk about what your cousins are doing these days.",
        "You meet {other} at a coffee shop. Discuss a difficult conversation you had with a family member.",
        "You and {other} are on a morning jog. Share something sweet your partner or spouse did recently.",
        "You see {other} at a community centre. Talk about how your family celebrates cultural traditions.",
        "You and {other} are at a PTA meeting. Chat about balancing work and family life.",
        "You run into {other} at the post office. Mention a care package you're sending to a relative.",
        "You and {other} are at a picnic. Talk about your childhood and how your family shaped who you are.",
        "You meet {other} at a restaurant. Discuss a new addition to the family — a baby, pet, or roommate.",
        "You and {other} are at a neighbourhood watch meeting. Chat about keeping your families safe.",
        "You bump into {other} at a hardware store. Talk about a home project your family is working on.",
        "You and {other} are at a park bench. Share worries about an aging parent.",
        "You see {other} at a yoga class. Talk about how you've been trying to spend more quality time with family.",
        "You and {other} are at a school fundraiser. Discuss your kids' friendships and social lives.",
    ],
    # ------------------------------------------------------------------
    "work": [
        "You meet {other} at a coffee shop before work. Talk about what's been happening at your jobs.",
        "You and {other} are grabbing lunch. Discuss a project or deadline you're dealing with.",
        "You run into {other} after work. Vent about a frustrating meeting or coworker situation.",
        "You see {other} at a networking event. Exchange thoughts on your career trajectories.",
        "You and {other} are at a bar after hours. Talk about whether you're happy in your current role.",
        "You bump into {other} on the commute. Chat about a new initiative at your workplace.",
        "You and {other} are at a weekend brunch. Discuss work-life balance and how you manage it.",
        "You meet {other} at the gym. Bring up a job opportunity or interview you've been considering.",
        "You and {other} are at a community event. Talk about industry trends that affect your work.",
        "You see {other} at a bookstore. Discuss a professional development course or certification.",
        "You and {other} are walking in the park. Share your thoughts on remote work versus office work.",
        "You run into {other} at a conference. Exchange opinions on a keynote speaker's ideas.",
        "You and {other} are at a dinner party. Talk about a mentor who influenced your career.",
        "You meet {other} at a co-working space. Discuss the pros and cons of freelancing.",
        "You bump into {other} at a train station. Chat about a raise or promotion you're hoping for.",
        "You and {other} are at a weekend market. Talk about switching careers or industries.",
        "You see {other} at a restaurant. Discuss a workplace policy that recently changed.",
        "You and {other} are catching up over the phone. Share how your team dynamics have evolved.",
        "You meet {other} at a volunteer event. Talk about finding meaning and purpose in your work.",
        "You and {other} are at a sports game. Discuss the stress of managing people or being managed.",
        "You run into {other} at a pharmacy. Mention how work has been affecting your stress levels.",
        "You and {other} are at a holiday party. Chat about year-end reviews and goal setting.",
        "You bump into {other} at a laundromat. Talk about a side project or business idea.",
        "You and {other} are at a museum. Discuss how automation or AI is changing your field.",
        "You see {other} at a dog park. Share a funny or absurd story from the office.",
        "You and {other} are at a bakery. Talk about negotiating salary or benefits.",
        "You meet {other} at a library. Discuss a book or article related to your profession.",
        "You and {other} are at a community garden. Chat about retirement planning and long-term goals.",
        "You run into {other} at a petrol station. Bring up a colleague who recently left or joined.",
        "You and {other} are at a pub quiz. Talk about what you'd do if you won the lottery and quit.",
    ],
    # ------------------------------------------------------------------
    "health": [
        "You meet {other} at the gym. Talk about your fitness routines and goals.",
        "You and {other} are at a juice bar. Discuss a new diet or eating habit you're trying.",
        "You run into {other} at a pharmacy. Chat about a health concern you've been dealing with.",
        "You see {other} at a park. Talk about how you've been managing stress lately.",
        "You and {other} are at a yoga class. Discuss the benefits of meditation or mindfulness.",
        "You bump into {other} at a doctor's waiting room. Share how a recent check-up went.",
        "You and {other} are at a farmers market. Talk about clean eating and nutrition.",
        "You meet {other} on a hiking trail. Discuss how being outdoors affects your mental health.",
        "You and {other} are at a swimming pool. Chat about recovery from an injury or surgery.",
        "You see {other} at a health food store. Bring up a supplement or vitamin you've been taking.",
        "You and {other} are at a cooking class. Talk about allergies or dietary restrictions.",
        "You run into {other} at a neighbourhood walk. Discuss sleep habits and how well you've been resting.",
        "You and {other} are at a spa. Chat about self-care routines and taking mental health days.",
        "You meet {other} at a running group. Talk about training for a race or physical challenge.",
        "You bump into {other} at a cafe. Discuss a health scare that made you rethink your habits.",
        "You and {other} are at a community centre. Talk about a wellness programme or health workshop.",
        "You see {other} at a dentist's office. Chat about dental health and that appointment you keep postponing.",
        "You and {other} are at a weight room. Discuss the mental benefits of regular exercise.",
        "You run into {other} at a smoothie shop. Bring up how your energy levels have been.",
        "You and {other} are at a blood drive. Talk about the importance of regular health screenings.",
        "You meet {other} at a physiotherapy clinic. Share tips on managing chronic pain.",
        "You and {other} are at a bike path. Discuss how you stay motivated to work out.",
        "You bump into {other} at a wellness retreat. Talk about burnout and how you've been coping.",
        "You and {other} are at a health fair. Chat about wearable fitness trackers and health data.",
        "You see {other} at an outdoor boot camp. Discuss how your body has changed as you've gotten older.",
        "You and {other} are at a sauna. Talk about hydration and how much water you actually drink.",
        "You run into {other} at an allergy clinic. Share experiences with seasonal allergies.",
        "You and {other} are at a martial arts studio. Discuss discipline and the mind-body connection.",
        "You meet {other} at a hospital cafeteria. Talk about visiting someone who's been unwell.",
        "You and {other} are at a stretching class. Chat about posture and the toll of desk work.",
    ],
    # ------------------------------------------------------------------
    "finance": [
        "You and {other} are grabbing coffee. Talk about budgeting and saving strategies.",
        "You meet {other} at a bank. Discuss mortgage rates or rent increases.",
        "You run into {other} at a store. Chat about a big purchase you're considering.",
        "You and {other} are at a dinner. Talk about investing — stocks, crypto, or real estate.",
        "You see {other} at a tax preparation office. Discuss how tax season went this year.",
        "You bump into {other} at a financial planning seminar. Share what you learned.",
        "You and {other} are at a bar. Chat about student loans or debt repayment.",
        "You meet {other} at a car dealership. Talk about financing a vehicle.",
        "You and {other} are at a community meeting. Discuss the cost of living in your area.",
        "You run into {other} at a grocery store. Chat about how food prices have changed.",
        "You and {other} are at a restaurant. Talk about tipping culture and service industry wages.",
        "You see {other} at a bookstore. Discuss a personal finance book you've read.",
        "You bump into {other} at a garage sale. Chat about frugality and finding good deals.",
        "You and {other} are at a retirement planning workshop. Share your long-term financial goals.",
        "You meet {other} at a co-working space. Talk about the financial side of freelancing.",
        "You and {other} are at a gym. Discuss the cost of gym memberships and fitness subscriptions.",
        "You run into {other} at an insurance office. Chat about health or life insurance decisions.",
        "You and {other} are at a housewarming party. Talk about the real estate market.",
        "You see {other} at a charity gala. Discuss charitable giving and tax deductions.",
        "You and {other} are on a walk. Chat about teaching kids about money.",
        "You bump into {other} at a credit union. Talk about emergency funds and financial safety nets.",
        "You and {other} are at a tech meetup. Discuss fintech apps you use for budgeting.",
        "You meet {other} at a thrift store. Share opinions on consumerism and mindful spending.",
        "You and {other} are at a potluck. Talk about meal planning to save money.",
        "You run into {other} at a gas station. Chat about fuel costs and commuting expenses.",
        "You and {other} are at a wedding. Discuss the cost of weddings and how to plan affordably.",
        "You see {other} at an estate sale. Talk about inheritance and family wealth.",
        "You and {other} are at a park. Chat about side hustles and extra income streams.",
        "You bump into {other} at a library. Discuss free resources for financial literacy.",
        "You and {other} are at a New Year's party. Talk about financial resolutions.",
    ],
    # ------------------------------------------------------------------
    "hobbies": [
        "You meet {other} at a craft store. Talk about a hobby project you've been working on.",
        "You and {other} are at a park. Discuss a new hobby you've picked up recently.",
        "You run into {other} at a music shop. Chat about instruments you play or want to learn.",
        "You see {other} at a bookshop. Share what you've been reading lately.",
        "You and {other} are at a community workshop. Talk about a skill you've been developing.",
        "You bump into {other} at a photography exhibit. Discuss your creative interests.",
        "You and {other} are at a gaming cafe. Chat about board games, video games, or tabletop RPGs.",
        "You meet {other} at a garden centre. Talk about your plants, garden, or balcony setup.",
        "You and {other} are at a flea market. Discuss collecting — stamps, vinyl, vintage items.",
        "You run into {other} at a pottery studio. Share your experience with a hands-on craft.",
        "You and {other} are at a dance class. Talk about learning new moves or styles.",
        "You see {other} at a woodworking shop. Chat about a DIY project you've completed or started.",
        "You and {other} are at a painting night. Discuss your artistic side and creative outlets.",
        "You bump into {other} at a fishing spot. Talk about outdoor hobbies and nature activities.",
        "You and {other} are at a sewing circle. Chat about making clothes, quilts, or other textile crafts.",
        "You meet {other} at a model shop. Discuss building models, drones, or RC cars.",
        "You and {other} are at a climbing gym. Talk about adventurous hobbies you've tried.",
        "You run into {other} at a cooking class. Share a recipe you've been perfecting.",
        "You and {other} are at a astronomy meetup. Chat about stargazing and the night sky.",
        "You see {other} at a comic book store. Discuss comics, manga, or graphic novels you enjoy.",
        "You and {other} are at a maker space. Talk about 3D printing or electronics projects.",
        "You bump into {other} at a bird-watching trail. Chat about wildlife observation.",
        "You and {other} are at a knitting group. Discuss a pattern or project you're working on.",
        "You meet {other} at a puzzle cafe. Talk about brain teasers and puzzle-solving.",
        "You and {other} are at an archery range. Chat about precision hobbies and focus.",
        "You run into {other} at a film screening. Discuss filmmaking or video editing as a hobby.",
        "You and {other} are at a calligraphy workshop. Talk about handwriting and lettering arts.",
        "You see {other} at a drone flying field. Chat about aerial photography or racing drones.",
        "You and {other} are at a language exchange meetup. Discuss learning a new language.",
        "You bump into {other} at a vintage car show. Talk about mechanical hobbies or restoration.",
    ],
    # ------------------------------------------------------------------
    "politics": [
        "You and {other} are at a cafe. Discuss a recent election or political development.",
        "You meet {other} at a town hall meeting. Share your views on a local policy issue.",
        "You run into {other} at a newsstand. Chat about a headline that caught your attention.",
        "You and {other} are at a dinner party. Talk about political polarisation and how to bridge divides.",
        "You see {other} at a protest or rally. Discuss the cause and your feelings about activism.",
        "You bump into {other} at a library. Chat about a political book or documentary you encountered.",
        "You and {other} are at a community forum. Talk about housing policy or zoning changes.",
        "You meet {other} at a voter registration drive. Discuss the importance of civic engagement.",
        "You and {other} are on a walk. Chat about how politics affects your daily life.",
        "You run into {other} at a bar. Debate the merits of a recent government decision.",
        "You and {other} are at a school board meeting. Discuss education policy and curriculum debates.",
        "You see {other} at a cultural festival. Talk about immigration policy and multiculturalism.",
        "You and {other} are at a union meeting. Chat about labour rights and workers' protections.",
        "You bump into {other} at a grocery store. Discuss government subsidies and food policy.",
        "You and {other} are at a park. Talk about environmental regulations and climate policy.",
        "You meet {other} at a legal aid clinic. Discuss criminal justice reform.",
        "You and {other} are at a fundraiser. Chat about campaign finance and political donations.",
        "You run into {other} at a hospital waiting room. Talk about healthcare policy.",
        "You and {other} are at a veterans event. Discuss military policy and foreign affairs.",
        "You see {other} at a tech conference. Chat about data privacy laws and tech regulation.",
        "You and {other} are at a senior centre. Discuss social security and pension policy.",
        "You bump into {other} at a neighbourhood meeting. Talk about policing and public safety.",
        "You and {other} are at a faith gathering. Chat about the role of religion in politics.",
        "You meet {other} at a debate watch party. Share your reactions to the candidates.",
        "You and {other} are at a co-op. Discuss economic inequality and wealth redistribution.",
        "You run into {other} at a bus stop. Chat about public transit funding and infrastructure.",
        "You and {other} are at a museum. Talk about how history shapes current political movements.",
        "You see {other} at a free speech event. Discuss censorship and media freedom.",
        "You and {other} are at a potluck. Chat about how your political views have changed over time.",
        "You bump into {other} at a farmers market. Talk about agricultural policy and food sovereignty.",
    ],
    # ------------------------------------------------------------------
    "food_cooking": [
        "You meet {other} at a farmers market. Talk about seasonal produce you're excited about.",
        "You and {other} are at a restaurant. Discuss a meal you recently cooked that turned out great.",
        "You run into {other} at a grocery store. Chat about a new ingredient you discovered.",
        "You see {other} at a cooking class. Share your favourite comfort food recipes.",
        "You and {other} are at a potluck. Talk about the dish you brought and how you made it.",
        "You bump into {other} at a bakery. Discuss baking — bread, pastries, or cakes.",
        "You and {other} are at a food festival. Chat about cuisines you've been wanting to try.",
        "You meet {other} at a spice shop. Talk about how spices transform a dish.",
        "You and {other} are at a wine tasting. Discuss food and wine pairings.",
        "You run into {other} at a butcher shop. Chat about meat cuts and cooking techniques.",
        "You and {other} are at a sushi bar. Talk about your favourite types of fish and preparation.",
        "You see {other} at a kitchen supply store. Discuss a new kitchen gadget or tool.",
        "You and {other} are at a barbecue. Share grilling tips and marinades.",
        "You bump into {other} at a deli. Chat about sandwich crafting and charcuterie boards.",
        "You and {other} are at a tea house. Talk about tea varieties and brewing methods.",
        "You meet {other} at an ice cream parlour. Discuss homemade desserts and sweet treats.",
        "You and {other} are at a food truck rally. Chat about street food and casual dining.",
        "You run into {other} at a health food store. Talk about cooking healthy on a budget.",
        "You and {other} are at a dinner party. Discuss meal prepping and weekly menus.",
        "You see {other} at a cheese shop. Chat about cheese varieties and fondue.",
        "You and {other} are at a breakfast spot. Talk about your morning routines and what you eat.",
        "You bump into {other} at a cookbook section. Discuss a cookbook author or food blogger you follow.",
        "You and {other} are at a noodle shop. Chat about your go-to pasta or noodle dishes.",
        "You meet {other} at a coffee roaster. Talk about coffee preparation methods.",
        "You and {other} are at a community kitchen. Discuss cooking for large groups.",
        "You run into {other} at a farmer's stand. Share a family recipe passed down through generations.",
        "You and {other} are at a food bank volunteer shift. Talk about food waste and sustainability.",
        "You see {other} at a fermentation workshop. Chat about making pickles, kimchi, or kombucha.",
        "You and {other} are at a brunch spot. Discuss food trends — plant-based, fermented, fusion.",
        "You bump into {other} at a pizza place. Talk about perfecting pizza dough at home.",
    ],
    # ------------------------------------------------------------------
    "travel": [
        "You meet {other} at a cafe. Talk about a trip you recently took or are planning.",
        "You and {other} are at a travel expo. Discuss dream destinations you want to visit.",
        "You run into {other} at an airport lounge. Chat about travel hacks and packing tips.",
        "You see {other} at a photo exhibit. Share stories from a memorable trip.",
        "You and {other} are at a hostel reunion. Talk about budget travel and backpacking adventures.",
        "You bump into {other} at a luggage store. Discuss travel gear and essentials.",
        "You and {other} are at a dinner. Chat about cultural experiences from your travels.",
        "You meet {other} at a language class. Talk about how travel has changed your worldview.",
        "You and {other} are at a road trip pit stop. Discuss your favourite road trip routes.",
        "You run into {other} at a national park. Chat about hiking and outdoor adventures abroad.",
        "You and {other} are at a boat show. Talk about cruise experiences or sailing trips.",
        "You see {other} at a travel bookshop. Discuss guidebooks and travel writing.",
        "You and {other} are at a reunion. Share a funny or scary travel mishap.",
        "You bump into {other} at a camping store. Chat about your favourite campsites.",
        "You and {other} are at a food court. Talk about the best food you've had while travelling.",
        "You meet {other} at a train station. Discuss rail travel and scenic train journeys.",
        "You and {other} are at a volunteer project. Chat about voluntourism and ethical travel.",
        "You run into {other} at a visa office. Talk about the bureaucracy of international travel.",
        "You and {other} are at a rooftop bar. Discuss your travel bucket list.",
        "You see {other} at a souvenir shop. Chat about meaningful souvenirs you've collected.",
        "You and {other} are at a neighbourhood event. Talk about local tourism and exploring your own city.",
        "You bump into {other} at a gym. Discuss how you stay fit while travelling.",
        "You and {other} are at a concert. Chat about music festivals you've attended in different cities.",
        "You meet {other} at a photography group. Talk about travel photography tips.",
        "You and {other} are at a ski lodge. Discuss winter travel and ski destinations.",
        "You run into {other} at a beach. Chat about your favourite coastal spots.",
        "You and {other} are at a historical site. Talk about history-focused travel experiences.",
        "You see {other} at a cooking class abroad. Discuss food-focused travel itineraries.",
        "You and {other} are at a wellness retreat. Chat about relaxation-focused holidays.",
        "You bump into {other} at a currency exchange. Talk about managing money while abroad.",
    ],
    # ------------------------------------------------------------------
    "technology": [
        "You meet {other} at a tech meetup. Talk about a gadget or app you've been using.",
        "You and {other} are at a cafe. Discuss how AI is changing everyday life.",
        "You run into {other} at an electronics store. Chat about a device you're thinking of buying.",
        "You see {other} at a hackathon. Talk about a side project or coding challenge.",
        "You and {other} are at a co-working space. Discuss productivity tools and workflows.",
        "You bump into {other} at a repair shop. Chat about right-to-repair and planned obsolescence.",
        "You and {other} are at a conference. Talk about a tech talk or demo that impressed you.",
        "You meet {other} at a bookstore. Discuss a tech book, podcast, or newsletter you follow.",
        "You and {other} are at a bar. Chat about social media trends and digital wellbeing.",
        "You run into {other} at a library. Talk about online privacy and data security.",
        "You and {other} are at a maker space. Discuss a hardware project — Arduino, Raspberry Pi, etc.",
        "You see {other} at a phone store. Chat about the latest smartphone features.",
        "You and {other} are at a dinner. Talk about smart home devices and home automation.",
        "You bump into {other} at a gaming event. Discuss gaming tech — consoles, VR, or PC builds.",
        "You and {other} are at a startup pitch night. Chat about tech entrepreneurship.",
        "You meet {other} at a data science meetup. Talk about how data is used in your industry.",
        "You and {other} are at a park. Discuss the ethics of technology — surveillance, bias, etc.",
        "You run into {other} at a gym. Chat about fitness tech and wearable devices.",
        "You and {other} are at a school event. Talk about kids and screen time.",
        "You see {other} at a robotics exhibition. Discuss the future of automation.",
        "You and {other} are at a photography club. Chat about camera tech and editing software.",
        "You bump into {other} at a coffee shop. Talk about cloud computing and remote infrastructure.",
        "You and {other} are at a security conference. Discuss cybersecurity threats and best practices.",
        "You meet {other} at a 3D printing lab. Talk about additive manufacturing and prototyping.",
        "You and {other} are at a music studio. Chat about music production software and equipment.",
        "You run into {other} at a ride-share pickup. Talk about self-driving cars and transport tech.",
        "You and {other} are at a neighbourhood meeting. Discuss broadband access and the digital divide.",
        "You see {other} at an e-waste collection. Chat about sustainable technology practices.",
        "You and {other} are at a film screening. Talk about visual effects and CGI technology.",
        "You bump into {other} at a drone show. Discuss commercial and recreational drone applications.",
    ],
    # ------------------------------------------------------------------
    "relationships": [
        "You meet {other} at a cafe. Talk about how a close friendship has evolved over time.",
        "You and {other} are at a bar. Discuss navigating a disagreement with someone you care about.",
        "You run into {other} at a park. Chat about how you make time for friends despite being busy.",
        "You see {other} at a dinner party. Talk about a new person you've met and clicked with.",
        "You and {other} are at a community event. Discuss what makes a good friend versus an acquaintance.",
        "You bump into {other} at a gym. Chat about how your social circle has changed over the years.",
        "You and {other} are at a book club. Talk about a relationship dynamic in a novel that resonated.",
        "You meet {other} at a wedding. Discuss what you think makes relationships last.",
        "You and {other} are at a coffee shop. Chat about setting boundaries with people.",
        "You run into {other} at a neighbourhood walk. Talk about reconnecting with an old friend.",
        "You and {other} are at a concert. Discuss how shared interests bring people together.",
        "You see {other} at a volunteer event. Chat about mentorship and role models in your life.",
        "You and {other} are at a brunch. Talk about how you handle conflict in relationships.",
        "You bump into {other} at a store. Discuss the difference between online and in-person friendships.",
        "You and {other} are at a housewarming. Chat about neighbours and building community.",
        "You meet {other} at a therapy waiting room. Talk about how therapy has affected your relationships.",
        "You and {other} are at a picnic. Discuss how having kids or not having kids changes friendships.",
        "You run into {other} at a class. Chat about romantic relationships and dating.",
        "You and {other} are at a game night. Talk about trust and vulnerability with friends.",
        "You see {other} at a funeral. Discuss grief and supporting each other through loss.",
        "You and {other} are at a reunion. Chat about people who've drifted away and why.",
        "You bump into {other} at a market. Talk about how you show appreciation for the people in your life.",
        "You and {other} are at a spa day. Discuss dealing with toxic or draining relationships.",
        "You meet {other} at a support group. Talk about loneliness and finding connection.",
        "You and {other} are at a dance class. Chat about how activities help you bond with others.",
        "You run into {other} at a dog park. Talk about the companionship pets provide.",
        "You and {other} are at a holiday gathering. Discuss family-of-choice versus blood family.",
        "You see {other} at a cultural event. Chat about cross-cultural friendships and understanding.",
        "You and {other} are at a cooking night. Talk about love languages and how you express care.",
        "You bump into {other} at a pharmacy. Discuss being there for friends during hard times.",
    ],
    # ------------------------------------------------------------------
    "education": [
        "You meet {other} at a library. Talk about something new you've been learning.",
        "You and {other} are at a cafe. Discuss an online course or certification you're taking.",
        "You run into {other} at a bookstore. Chat about a non-fiction book that taught you something.",
        "You see {other} at a school event. Talk about the education system and how it's changed.",
        "You and {other} are at a workshop. Discuss the value of formal education versus self-teaching.",
        "You bump into {other} at a university campus. Chat about your college experiences.",
        "You and {other} are at a study group. Talk about effective study techniques.",
        "You meet {other} at a career fair. Discuss skills that matter most in today's job market.",
        "You and {other} are at a tutoring centre. Chat about helping kids with homework.",
        "You run into {other} at a museum. Talk about learning through hands-on experience.",
        "You and {other} are at a lecture. Discuss a topic that surprised or challenged you.",
        "You see {other} at a community college. Chat about going back to school as an adult.",
        "You and {other} are at a science fair. Talk about encouraging curiosity in children.",
        "You bump into {other} at a co-working space. Discuss podcasts or YouTube channels you learn from.",
        "You and {other} are at a coding bootcamp. Chat about learning to code or picking up tech skills.",
        "You meet {other} at a language exchange. Talk about the challenge and reward of learning a language.",
        "You and {other} are at a teachers' meeting. Discuss burnout and motivation in education.",
        "You run into {other} at a graduation ceremony. Chat about milestones and what comes next.",
        "You and {other} are at a philosophy discussion group. Talk about big ideas and critical thinking.",
        "You see {other} at an art school open house. Discuss creative education and its importance.",
        "You and {other} are at a mentoring programme. Chat about the impact of a good teacher.",
        "You bump into {other} at a training session. Talk about professional development at work.",
        "You and {other} are at a debate club. Discuss the art of argumentation and rhetoric.",
        "You meet {other} at a homeschooling meetup. Chat about alternative education approaches.",
        "You and {other} are at a maths competition. Talk about the beauty of problem-solving.",
        "You run into {other} at a TED talk event. Discuss an idea worth spreading.",
        "You and {other} are at a research symposium. Chat about academic research and publishing.",
        "You see {other} at a financial literacy class. Talk about skills schools should teach but don't.",
        "You and {other} are at a first aid course. Discuss practical life skills everyone should know.",
        "You bump into {other} at an alumni event. Chat about how your education shaped your life.",
    ],
    # ------------------------------------------------------------------
    "entertainment": [
        "You meet {other} at a cinema. Talk about a film you recently watched.",
        "You and {other} are at a concert. Discuss music you've been listening to.",
        "You run into {other} at a bookshop. Chat about a TV series you've been binge-watching.",
        "You see {other} at a comedy show. Talk about comedians or shows that make you laugh.",
        "You and {other} are at a streaming watch party. Discuss what's worth watching right now.",
        "You bump into {other} at a record store. Chat about albums that shaped your music taste.",
        "You and {other} are at a theatre. Talk about a play or musical you enjoyed.",
        "You meet {other} at a gaming cafe. Discuss a video game you've been playing.",
        "You and {other} are at a trivia night. Chat about pop culture knowledge and guilty pleasures.",
        "You run into {other} at a podcast recording. Talk about podcasts you recommend.",
        "You and {other} are at a festival. Discuss your favourite live performances.",
        "You see {other} at an art gallery opening. Chat about visual art and what moves you.",
        "You and {other} are at a karaoke bar. Talk about songs that are impossible not to sing along to.",
        "You bump into {other} at a bookshelf swap. Discuss genres you love and genres you avoid.",
        "You and {other} are at a film discussion group. Chat about a movie's deeper meaning or symbolism.",
        "You meet {other} at a magic show. Talk about spectacle and showmanship in entertainment.",
        "You and {other} are at a rooftop movie screening. Discuss classic films versus modern ones.",
        "You run into {other} at a dance performance. Chat about dance as an art form.",
        "You and {other} are at a music festival. Talk about discovering new bands and artists.",
        "You see {other} at a board game night. Discuss your favourite games and strategies.",
        "You and {other} are at an improv show. Chat about the art of spontaneous comedy.",
        "You bump into {other} at a vinyl fair. Talk about nostalgia and retro entertainment.",
        "You and {other} are at an anime convention. Discuss anime, manga, or fan culture.",
        "You meet {other} at a food and film pairing event. Chat about themed entertainment nights.",
        "You and {other} are at a stand-up open mic. Talk about humour styles you appreciate.",
        "You run into {other} at a streaming service launch event. Discuss the state of streaming.",
        "You and {other} are at a documentary screening. Chat about real-life stories that captivated you.",
        "You see {other} at a Shakespeare festival. Talk about timeless stories and adaptations.",
        "You and {other} are at an escape room. Discuss puzzle-based and immersive entertainment.",
        "You bump into {other} at a circus performance. Chat about spectacle and wonder.",
    ],
    # ------------------------------------------------------------------
    "sports": [
        "You meet {other} at a sports bar. Talk about a recent game or match.",
        "You and {other} are at a gym. Discuss your workout routines and personal records.",
        "You run into {other} at a running track. Chat about training for a race.",
        "You see {other} at a sports equipment store. Talk about gear upgrades you're considering.",
        "You and {other} are at a basketball court. Discuss your favourite teams and players.",
        "You bump into {other} at a swimming pool. Chat about competitive swimming or water sports.",
        "You and {other} are at a football viewing party. Talk about the season so far.",
        "You meet {other} at a tennis court. Discuss improving your game and technique.",
        "You and {other} are at a cycling event. Chat about routes, bikes, and cycling culture.",
        "You run into {other} at a martial arts dojo. Talk about discipline and training.",
        "You and {other} are at a golf course. Discuss the mental game and strategy.",
        "You see {other} at a rock climbing gym. Chat about bouldering and outdoor climbing.",
        "You and {other} are at a yoga studio. Talk about flexibility and cross-training for sport.",
        "You bump into {other} at a sports medicine clinic. Discuss injury prevention and recovery.",
        "You and {other} are at a rowing club. Chat about team sports versus individual sports.",
        "You meet {other} at a sports auction. Talk about memorabilia and fandom.",
        "You and {other} are at a cricket match. Discuss the strategy and pace of the game.",
        "You run into {other} at a skate park. Chat about skateboarding or rollerblading.",
        "You and {other} are at a boxing gym. Talk about the physicality and discipline of combat sports.",
        "You see {other} at a triathlon registration. Discuss multi-sport training challenges.",
        "You and {other} are at a fantasy league draft. Chat about your picks and strategy.",
        "You bump into {other} at a surfing beach. Talk about wave conditions and surf culture.",
        "You and {other} are at a volleyball court. Discuss beach versus indoor volleyball.",
        "You meet {other} at a motorsport event. Chat about racing and your favourite drivers.",
        "You and {other} are at an Olympic watch party. Talk about your favourite Olympic moments.",
        "You run into {other} at a badminton court. Discuss underrated sports you enjoy.",
        "You and {other} are at a coaching seminar. Chat about what makes a great coach.",
        "You see {other} at a sports documentary screening. Talk about athletes who inspire you.",
        "You and {other} are at a parkour meetup. Discuss movement, agility, and urban athletics.",
        "You bump into {other} at a ping-pong club. Chat about casual games and competitive spirit.",
    ],
    # ------------------------------------------------------------------
    "spirituality": [
        "You meet {other} at a quiet cafe. Talk about what gives your life meaning.",
        "You and {other} are at a meditation group. Discuss your meditation practice and experiences.",
        "You run into {other} at a place of worship. Chat about your faith or spiritual journey.",
        "You see {other} at a nature retreat. Talk about finding peace in the natural world.",
        "You and {other} are at a philosophy discussion. Discuss big questions — purpose, mortality, free will.",
        "You bump into {other} at a bookstore. Chat about a spiritual or philosophical text you've read.",
        "You and {other} are at a yoga session. Talk about the spiritual side of yoga beyond the physical.",
        "You meet {other} at a grief support circle. Discuss how spirituality helps you cope with loss.",
        "You and {other} are at a mindfulness workshop. Chat about being present and aware.",
        "You run into {other} at a charity event. Talk about service, compassion, and giving back.",
        "You and {other} are at a sunset viewing spot. Discuss moments of awe and wonder.",
        "You see {other} at a journaling workshop. Chat about reflective writing and self-discovery.",
        "You and {other} are at a community garden. Talk about patience, growth, and cycles of nature.",
        "You bump into {other} at a prayer group. Discuss how prayer or reflection anchors your day.",
        "You and {other} are at a labyrinth walk. Chat about walking meditation and contemplative practice.",
        "You meet {other} at an interfaith dialogue. Talk about learning from different spiritual traditions.",
        "You and {other} are at a sound bath. Discuss the role of ritual and ceremony in your life.",
        "You run into {other} at a hospice volunteer shift. Chat about mortality and end-of-life wisdom.",
        "You and {other} are at a pilgrimage stop. Talk about sacred places you've visited.",
        "You see {other} at a gratitude circle. Discuss the practice of counting your blessings.",
        "You and {other} are at a retreat centre. Chat about solitude and its spiritual value.",
        "You bump into {other} at a candle-lighting ceremony. Talk about remembrance and honouring the past.",
        "You and {other} are at a drum circle. Discuss communal spiritual experiences.",
        "You meet {other} at a forest bathing walk. Chat about the Japanese concept of shinrin-yoku.",
        "You and {other} are at a book club. Talk about how stories and myths carry spiritual truths.",
        "You run into {other} at a fasting group. Discuss the discipline and clarity that fasting brings.",
        "You and {other} are at a star-gazing night. Chat about the cosmos and your place in it.",
        "You see {other} at a healing circle. Talk about forgiveness and letting go.",
        "You and {other} are at a tai chi class. Discuss energy, flow, and balance in daily life.",
        "You bump into {other} at a sacred music concert. Chat about how music connects you to something deeper.",
    ],
    # ------------------------------------------------------------------
    "housing": [
        "You meet {other} in your building lobby. Talk about a maintenance issue or repair.",
        "You and {other} are at an open house. Discuss the housing market in your area.",
        "You run into {other} at a hardware store. Chat about a home renovation project.",
        "You see {other} at a furniture showroom. Talk about decorating or furnishing a room.",
        "You and {other} are at a neighbourhood meeting. Discuss noise, parking, or shared spaces.",
        "You bump into {other} at a garden centre. Chat about landscaping or yard work.",
        "You and {other} are at a housewarming party. Talk about the joys and stresses of moving.",
        "You meet {other} at a real estate office. Discuss renting versus buying.",
        "You and {other} are at a block party. Chat about your neighbours and the community vibe.",
        "You run into {other} at a cleaning supply store. Talk about deep cleaning and decluttering.",
        "You and {other} are at a co-op board meeting. Discuss building policies and shared decisions.",
        "You see {other} at a paint store. Chat about choosing colours and interior design.",
        "You and {other} are at a community safety meeting. Talk about home security and safety.",
        "You bump into {other} at a plumbing supply shop. Discuss dealing with contractors and tradespeople.",
        "You and {other} are at a tenant rights workshop. Chat about landlord-tenant dynamics.",
        "You meet {other} at a rooftop gathering. Talk about the pros and cons of your living situation.",
        "You and {other} are at a yard sale. Discuss downsizing or organising your home.",
        "You run into {other} at an IKEA. Chat about affordable furniture and small-space living.",
        "You and {other} are at a sustainability fair. Talk about energy efficiency and green homes.",
        "You see {other} at a moving truck rental. Discuss the logistics and emotions of relocating.",
        "You and {other} are at a flooring store. Chat about home improvement priorities.",
        "You bump into {other} at a locksmith. Talk about home safety and feeling secure.",
        "You and {other} are at a strata meeting. Discuss shared facilities and building maintenance fees.",
        "You meet {other} at an architecture tour. Chat about home styles and what you'd love to live in.",
        "You and {other} are at a pest control office. Talk about dealing with pests at home.",
        "You run into {other} at an appliance store. Discuss upgrading kitchen or laundry appliances.",
        "You and {other} are at a storage unit facility. Chat about having too much stuff.",
        "You see {other} at a solar panel installation event. Talk about renewable energy at home.",
        "You and {other} are at a home insurance office. Discuss what to insure and why.",
        "You bump into {other} at a window and door showroom. Chat about insulation and weatherproofing.",
    ],
    # ------------------------------------------------------------------
    "daily_logistics": [
        "You meet {other} at a bus stop. Talk about your commute and how you get around.",
        "You and {other} are at a grocery store. Discuss meal planning and shopping strategies.",
        "You run into {other} at a post office. Chat about errands that have been piling up.",
        "You see {other} at a laundromat. Talk about your weekly routine and how you organise your time.",
        "You and {other} are at a car service centre. Discuss vehicle maintenance or transport woes.",
        "You bump into {other} at a bank. Chat about bill paying and administrative tasks.",
        "You and {other} are at a pharmacy. Talk about managing prescriptions and appointments.",
        "You meet {other} at a dry cleaner. Discuss the little tasks that eat up your free time.",
        "You and {other} are at a petrol station. Chat about fuel costs and your daily driving route.",
        "You run into {other} at a school drop-off. Talk about the morning rush and scheduling chaos.",
        "You and {other} are at a dentist's waiting room. Discuss how you keep track of appointments.",
        "You see {other} at a courier pickup point. Chat about online shopping and delivery logistics.",
        "You and {other} are at a calendar planning workshop. Talk about time management systems.",
        "You bump into {other} at a cobbler or tailor. Discuss small repairs and maintenance you've been putting off.",
        "You and {other} are at a recycling centre. Chat about waste management and sorting habits.",
        "You meet {other} at a parking lot. Talk about parking headaches and city navigation.",
        "You and {other} are at a mobile phone store. Discuss phone plans and contracts.",
        "You run into {other} at a utility company office. Chat about dealing with bills and service issues.",
        "You and {other} are at a vet's office. Talk about pet care logistics — feeding, walks, vet visits.",
        "You see {other} at a train platform. Discuss public transit reliability and alternatives.",
        "You and {other} are at a notary office. Chat about paperwork and bureaucratic tasks.",
        "You bump into {other} at a key cutting shop. Talk about small everyday tasks that take forever.",
        "You and {other} are at a children's activity centre. Discuss coordinating kids' schedules.",
        "You meet {other} at a storage locker. Chat about seasonal organisation and rotating gear.",
        "You and {other} are at a DMV or licensing office. Talk about the pain of renewing documents.",
        "You run into {other} at a roadside assistance call. Discuss backup plans and contingencies.",
        "You and {other} are at a supermarket self-checkout. Chat about the small annoyances of daily life.",
        "You see {other} at a home delivery dropoff. Talk about subscription services you use.",
        "You and {other} are at a community bulletin board. Discuss neighbourhood resources and services.",
        "You bump into {other} at a shoe repair shop. Chat about how you prioritise your daily to-do list.",
    ],
}


def get_prompts(domain: str) -> List[str]:
    """Return the routine prompts for a given domain, or empty list if unknown."""
    return ROUTINE_PROMPTS.get(domain, [])


def all_domains() -> List[str]:
    """Return the list of all domain IDs with routine prompts."""
    return list(ROUTINE_PROMPTS.keys())
