"""Compute human-vs-4o-mini-judge agreement from calibration labels.

Inputs:
  --labels: path to human_calibration_labels_*.json (keys = instance ids, values = 0/1/'skip')
  --pool: path to docs/human_calibration/sample.json (metadata['sample'] list with judge_correct)

Outputs:
  --tex:  LaTeX table to paper/tables/judge_human.tex
  --json: per-dim + overall metrics dump (for downstream use)

Metrics:
  - n: labels used (excludes 'skip' and ids not in pool)
  - agreement: fraction where human_label == judge_correct_int
  - cohen_kappa: Cohen's kappa for binary human vs judge labels
  - per-dim breakdown
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path


def cohen_kappa(a: list[int], b: list[int]) -> float:
    n = len(a)
    if n == 0:
        return float("nan")
    agree = sum(1 for x, y in zip(a, b) if x == y) / n
    pa1 = sum(a) / n
    pb1 = sum(b) / n
    pe = pa1 * pb1 + (1 - pa1) * (1 - pb1)
    if pe >= 1.0:
        return float("nan")
    return (agree - pe) / (1 - pe)


DIM_LABELS = {
    "d1": "Conflict",
    "d2": "Anaphora",
    "d3": "Confabulation",
    "d4": "Permission",
    "d5": "Cloze",
    "d6": "Metadata",
    "d7": "QA",
    "d8": "Temporal",
    "d9": "Negation",
    "d10": "Counterfactual",
    "d11": "Exception",
}


def normalize_dim(dim: str) -> str:
    if dim.startswith("d") and "_" in dim:
        return dim.split("_")[0]
    return dim


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--labels", required=True)
    ap.add_argument("--pool", default="docs/human_calibration/sample.json")
    ap.add_argument("--tex", default="paper/tables/judge_human.tex")
    ap.add_argument("--json", default="paper/tables/judge_human_metrics.json")
    args = ap.parse_args()

    labels_blob = json.loads(Path(args.labels).read_text())
    labels = labels_blob.get("labels", labels_blob)

    pool_blob = json.loads(Path(args.pool).read_text())
    pool = {row["id"]: row for row in pool_blob.get("sample", [])}

    pairs = []
    skipped = 0
    unmatched = 0
    per_dim: dict[str, list[tuple[int, int]]] = defaultdict(list)

    for iid, hval in labels.items():
        if hval == "skip":
            skipped += 1
            continue
        if iid not in pool:
            unmatched += 1
            continue
        h = int(hval)
        j = int(bool(pool[iid]["judge_correct"]))
        pairs.append((h, j))
        dim = normalize_dim(pool[iid]["dim"])
        per_dim[dim].append((h, j))

    if not pairs:
        print("No usable pairs; aborting.", file=sys.stderr)
        sys.exit(1)

    h_all = [p[0] for p in pairs]
    j_all = [p[1] for p in pairs]
    overall = {
        "n": len(pairs),
        "agreement": sum(1 for x, y in pairs if x == y) / len(pairs),
        "cohen_kappa": cohen_kappa(h_all, j_all),
        "human_pos_rate": sum(h_all) / len(h_all),
        "judge_pos_rate": sum(j_all) / len(j_all),
    }

    dim_rows = []
    for dim in sorted(per_dim.keys(), key=lambda d: int(d.lstrip("d"))):
        ps = per_dim[dim]
        h = [p[0] for p in ps]
        j = [p[1] for p in ps]
        dim_rows.append({
            "dim": dim,
            "name": DIM_LABELS.get(dim, dim),
            "n": len(ps),
            "agreement": sum(1 for x, y in ps if x == y) / len(ps),
            "cohen_kappa": cohen_kappa(h, j),
            "human_pos_rate": sum(h) / len(h),
            "judge_pos_rate": sum(j) / len(j),
        })

    metrics = {
        "meta": {
            "labels_path": str(args.labels),
            "pool_path": str(args.pool),
            "labels_total": len(labels),
            "skipped": skipped,
            "unmatched": unmatched,
            "used": len(pairs),
            "target": labels_blob.get("metadata", {}).get("n"),
        },
        "overall": overall,
        "per_dim": dim_rows,
    }
    Path(args.json).write_text(json.dumps(metrics, indent=2))

    lines = [
        "% Auto-generated by scripts/analyze_judge_human.py.",
        "% Source labels: " + Path(args.labels).name,
        "\\begin{table}[h]",
        "\\centering",
        "\\small",
        "\\caption{Judge--human calibration on \\benchL{}. "
        "Human annotator vs.\\ gpt-4o-mini judge binary verdicts "
        f"($n={len(pairs)}$ of a target 500; {skipped} skipped by annotator). "
        "Values are exact agreement and Cohen's $\\kappa$ per dimension and overall.}",
        "\\label{tab:judge-human}",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "Dimension & $n$ & Agreement & $\\kappa$ \\\\",
        "\\midrule",
    ]
    for r in dim_rows:
        lines.append(
            f"{r['name']} & {r['n']} & {r['agreement']:.3f} & {r['cohen_kappa']:.3f} \\\\"
        )
    lines += [
        "\\midrule",
        f"\\textbf{{Overall}} & {overall['n']} & {overall['agreement']:.3f} "
        f"& {overall['cohen_kappa']:.3f} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    Path(args.tex).write_text("\n".join(lines) + "\n")

    print(f"[ok] used={len(pairs)}  skipped={skipped}  unmatched={unmatched}")
    print(f"[ok] overall agreement={overall['agreement']:.3f}  "
          f"kappa={overall['cohen_kappa']:.3f}")
    for r in dim_rows:
        print(f"  {r['dim']:>4}  n={r['n']:3d}  agree={r['agreement']:.3f}  "
              f"kappa={r['cohen_kappa']:.3f}")
    print(f"[ok] wrote {args.tex}")
    print(f"[ok] wrote {args.json}")


if __name__ == "__main__":
    main()
